"""discovery

Revision ID: 94e197d699bd
Revises: 1c9d55a9c008
Create Date: 2026-10-07 18:32:25.861948
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "94e197d699bd"
down_revision: str | None = "1c9d55a9c008"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "competitor_suggestions",
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("website", sa.String(length=500), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("is_selected", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
            name=op.f("competitor_suggestions_run_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("competitor_suggestions_pkey")),
    )
    op.create_index(
        op.f("ix_competitor_suggestions_run_id"), "competitor_suggestions", ["run_id"], unique=False
    )
    op.add_column(
        "runs",
        sa.Column(
            "kind",
            sa.Enum(
                "check",
                "company_discovery",
                "page_discovery",
                name="runkind",
                native_enum=False,
                length=32,
            ),
            server_default="check",
            nullable=False,
        ),
    )
    op.add_column("runs", sa.Column("competitor_id", sa.Uuid(), nullable=True))
    op.create_index(op.f("ix_runs_competitor_id"), "runs", ["competitor_id"], unique=False)
    op.create_foreign_key(
        op.f("runs_competitor_id_fkey"),
        "runs",
        "competitors",
        ["competitor_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "tracked_pages", sa.Column("rationale", sa.Text(), server_default="", nullable=False)
    )
    op.add_column("workspaces", sa.Column("website", sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workspaces", "website")
    op.drop_column("tracked_pages", "rationale")
    op.drop_constraint(op.f("runs_competitor_id_fkey"), "runs", type_="foreignkey")
    op.drop_index(op.f("ix_runs_competitor_id"), table_name="runs")
    op.drop_column("runs", "competitor_id")
    op.drop_column("runs", "kind")
    op.drop_index(op.f("ix_competitor_suggestions_run_id"), table_name="competitor_suggestions")
    op.drop_table("competitor_suggestions")
    # ### end Alembic commands ###
